language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
script:
  - travis_retry npm test
env:
  global:
    - secure: SIFjFoLiYyZSqxltulANunQMyT6cPWr9isJJ0Lm8qr2pB30lLwsXFhkoisO2+J/K0Jk/e3pC4WTUXjpq1Sr/J3frXzZeLwE//Sed+92uxTGaZz+/1B08CWcelY09TLqtfVl1VIJZ+qihDcDdWhFGZPmuqpHCdTXzu2QJ6SiNrcs=
    - secure: f3XAu4HdzVFS4kOpEAKyYg+Iv9BHOZfRxzRpj15utYNbuhLhZitAjC/IWuchALm4u9EFPdowkIuB/9n2+VajrR8UKQcy23S6ClBCUP5eptwrMTWTbRP1vx3A4mdeoUy2FW7DVgZCWh5oe6o8MwX8rd1f6ZYAucBub4gMpp3GcEU=
